backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "berita"
    label: "Berita"
    folder: "admin-data/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Gambar", name: "image", widget: "image" }
      - { label: "Isi", name: "body", widget: "markdown" }